export const actionTypes ={
    SET_PRODUCTS:"SET_PRODUCTS",
    SET_SELECTED_PRODUCTS:"SET_SELECTED_PRODUCTS",
    SET_CART_DATA:"SET_CART_DATA",
    REMOVE_CART_DATA:"REMOVE_CART_DATA",
    PLACE_ORDER:"PLACE_ORDER",
    DELETE_SELECTED_PRODUCTS:"DELETE_SELECTED_PRODUCTS",
    SETLOGINVALUE:"SETLOGINVALUE"
}